services:

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - MONGO_URL=mongodb://host.docker.internal:27017/?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+2.6.0 
      - GEMINI_API=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      - UPSTASH_TOKEN=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: http://backend:8000
    ports:
      - "4173:4173"
    depends_on:
      - backend
